// Next components
import type { Metadata } from "next";
import dynamic from "next/dynamic";

import SideNavBar from "@/components/SideNavBar/SideNavBar";

// Stylings
import "bootstrap/dist/css/bootstrap.min.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import "./globals.css";
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

const DynamicBootstrap = dynamic(
  () => require("bootstrap/dist/js/bootstrap.min.js"),
  { ssr: false }
);

export const metadata: Metadata = {
  title: "Web3 Browser",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="container-fluid">
        <div className="row">
          <div className="col-md-3 pt-2">
            <SideNavBar />
          </div>
          <div className="col">
            <div className="row">
              <div className="col">{children}</div>
            </div>
            <div className="row">
              <div className="col">This is copyright</div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
